version: '2'
services:
  xamsambokk-app:
    image: xamsambokk
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://xamsambokk-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=xamsambokk
      - JHIPSTER_CACHE_REDIS_SERVER=redis://xamsambokk-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://xamsambokk-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://xamsambokk-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://xamsambokk-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
  xamsambokk-mongodb:
    extends:
      file: mongodb.yml
      service: xamsambokk-mongodb
  xamsambokk-redis:
    extends:
      file: redis.yml
      service: xamsambokk-redis
  xamsambokk-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: xamsambokk-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
